#!/bang/bash

#Author : Nawaz

#Location: London

#I am write this file to lear Git tool
#############################

Hi today is Dec 4 2024.
I will be consistence on my learning path as I have lot of commitments and responsibities.

Hi I am from Mumbai region.
First commit from mumbai.
