#!/bang/bash

#Author : Nawaz

#Location: London

#I am write this file to lear Git tool
#############################

Hi today is Dec 4 2024.
I will be consistence on my learning path as I have lot of commitments and responsibities.

Hi I am from Mumbai region.
First commit from mumbai.

I am learnig Pull and Push of the frile from central repo

This is the new commit from Mumbai region.

Hi its a new mornig of learning Git and Ill make sure that Ill complete the git subject today.

Hello this is from Mumbai region.
I am get intrested to learn Devops by grace Almighty Allah.
I love you Alla.
La haula wala quawatha illa billa
